<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LensCraft - Custom Photography Booking</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Inter', sans-serif;
        }

        .step-content {
            display: none;
        }

        .step-content.active {
            display: block;
            animation: slideUp 0.4s ease-out;
        }

        @keyframes slideUp {
            from {
                opacity: 0;
                transform: translateY(10px);
            }

            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        .selected-card {
            border-color: #dc143c !important;
            background-color: #fff5f5 !important;
        }

        .selected-card .check-icon {
            display: flex !important;
        }

        /* Range Slider */
        input[type=range]::-webkit-slider-thumb {
            -webkit-appearance: none;
            height: 16px;
            width: 16px;
            border-radius: 50%;
            background: #dc143c;
            cursor: pointer;
            margin-top: -4px;
        }

        input[type=range]::-webkit-slider-runnable-track {
            width: 100%;
            height: 8px;
            cursor: pointer;
            background: #e5e7eb;
            border-radius: 4px;
        }

        .bckbtn {
            height: 40px;
            width: 150px;
            background-color: #dc143c;
            color: white;
            border-radius: 20px;
            border: none;
        }

        .bckbtn:hover {
            background-color: orangered;
            cursor: pointer;
        }
    </style>
    <script type="importmap">
        {
  "imports": {
    "react": "https://aistudiocdn.com/react@^19.2.0",
    "lucide-react": "https://aistudiocdn.com/lucide-react@^0.554.0",
    "react/": "https://aistudiocdn.com/react@^19.2.0/"
  }
}
</script>
</head>

<body class="bg-gray-50 text-gray-900 pb-24">

    <!-- Global Back Button -->
    <div class="fixed top-4 left-4 z-50">
        <button id="global-back" onclick="app.prevStep()" class="hidden flex items-center px-4 py-2 bg-[#dc143c] text-white rounded-full font-bold shadow-lg hover:bg-white hover:text-[#dc143c] border border-transparent hover:border-[#dc143c] transition-all text-sm uppercase">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                <path d="M15 18l-6-6 6-6" />
            </svg> Back
        </button>
    </div>

    <!-- Header -->
    <header class="bg-[#1a1a1a] text-white py-12 mb-8 shadow-md relative overflow-hidden">
        <div>
            <a href="<?= page("users/home") ?>"><button class="bckbtn">Back to Home</button></a>
        </div>
        <div class="container mx-auto px-4 text-center relative z-10">

            <h1 class="text-4xl md:text-5xl font-bold text-[#dc143c] mb-3 flex items-center justify-center gap-3">
                <svg class="w-8 h-8 md:w-10 md:h-10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
                    <circle cx="12" cy="13" r="4" />
                </svg>
                LensCraft Booking
            </h1>
            <p class="text-gray-300 text-lg tracking-wide">Design Your Perfect Photography Experience</p>
        </div>
    </header>

    <div class="container mx-auto px-4 max-w-5xl">

        <!-- Progress Steps -->
        <div class="mb-10 relative px-4">
            <div class="absolute top-5 left-0 right-0 h-1 bg-gray-200 z-0 mx-8 md:mx-16 rounded-full"></div>
            <div id="progress-bar" class="absolute top-5 left-0 h-1 bg-[#dc143c] z-0 mx-8 md:mx-16 rounded-full transition-all duration-500 ease-in-out" style="width: 0%"></div>

            <div class="relative z-10 flex justify-between w-full" id="step-indicators">
                <!-- Steps generated by JS based on count, or hardcoded below -->
                <div class="flex flex-col items-center step-indicator" data-step="1">
                    <div class="w-10 h-10 rounded-full flex items-center justify-center font-bold text-sm border-2 bg-[#dc143c] border-[#dc143c] text-white transition-all">1</div>
                    <span class="mt-2 text-xs font-bold text-[#dc143c]">Photographer</span>
                </div>
                <div class="flex flex-col items-center step-indicator" data-step="2">
                    <div class="w-10 h-10 rounded-full flex items-center justify-center font-bold text-sm border-2 bg-white border-gray-300 text-gray-400 transition-all">2</div>
                    <span class="mt-2 text-xs font-medium text-gray-400">Packages</span>
                </div>
                <div class="flex flex-col items-center step-indicator" data-step="3">
                    <div class="w-10 h-10 rounded-full flex items-center justify-center font-bold text-sm border-2 bg-white border-gray-300 text-gray-400 transition-all">3</div>
                    <span class="mt-2 text-xs font-medium text-gray-400">Customize</span>
                </div>
                <div class="flex flex-col items-center step-indicator" data-step="4">
                    <div class="w-10 h-10 rounded-full flex items-center justify-center font-bold text-sm border-2 bg-white border-gray-300 text-gray-400 transition-all">4</div>
                    <span class="mt-2 text-xs font-medium text-gray-400">Features</span>
                </div>
                <div class="flex flex-col items-center step-indicator" data-step="5">
                    <div class="w-10 h-10 rounded-full flex items-center justify-center font-bold text-sm border-2 bg-white border-gray-300 text-gray-400 transition-all">5</div>
                    <span class="mt-2 text-xs font-medium text-gray-400">Details</span>
                </div>
                <div class="flex flex-col items-center step-indicator" data-step="6">
                    <div class="w-10 h-10 rounded-full flex items-center justify-center font-bold text-sm border-2 bg-white border-gray-300 text-gray-400 transition-all">6</div>
                    <span class="mt-2 text-xs font-medium text-gray-400">Review</span>
                </div>
            </div>
        </div>

        <!-- Main Card -->
        <div class="bg-white rounded-3xl shadow-xl p-6 md:p-10 mb-20 border border-gray-100 min-h-[500px] flex flex-col">

            <!-- STEP 1: PHOTOGRAPHER -->
            <div id="step-1" class="step-content active">
                <h2 class="text-3xl font-bold text-gray-900 mb-2">Choose Your Artist</h2>
                <p class="text-gray-600 mb-8">Select the photographer whose style matches your vision.</p>

                <div id="profilephotgrapher" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                    <!-- Photographer 1 -->


                    <!-- Photographer 2 -->


                    <!-- Photographer 3 -->


                    <!-- Photographer 4 -->

                </div>
            </div>

            <!-- STEP 2: PACKAGES -->
            <div id="step-2" class="step-content">
                <h2 class="text-3xl font-bold text-gray-900 mb-2">Build Your Package</h2>
                <p class="text-gray-600 mb-8">Select the core services you need.</p>

                <!-- Category: Coverage -->
                <div class="mb-8">
                    <h3 class="text-lg font-bold text-[#dc143c] uppercase border-b pb-2 mb-4">Coverage</h3>
                    <div id="coveragestep" class="space-y-3">


                    </div>
                </div>

                <!-- Category: Pre-Event -->
                <div class="mb-8">
                    <h3 class="text-lg font-bold text-[#dc143c] uppercase border-b pb-2 mb-4">Pre-Event</h3>
                    <div id="preevent" class="space-y-3">

                    </div>
                </div>

                <!-- Category: Equipment -->
                <div class="mb-8">
                    <h3 class="text-lg font-bold text-[#dc143c] uppercase border-b pb-2 mb-4">Equipment</h3>
                    <div id="equipment" class="space-y-3">

                    </div>
                </div>
            </div>

            <!-- STEP 3: CUSTOMIZE -->
            <div id="step-3" class="step-content">
                <h2 class="text-3xl font-bold text-gray-900 mb-2">Fine Tune Details</h2>
                <p class="text-gray-600 mb-8">Adjust specific quantities.</p>

                <div class="bg-gray-50 p-8 rounded-2xl border border-gray-200 space-y-10">
                    <div>
                        <div class="flex justify-between mb-4">
                            <label class="font-bold text-gray-900">Additional Hours</label>
                            <span id="display-hours" class="font-bold text-[#dc143c]">No extra hours</span>
                        </div>
                        <input type="range" id="input-hours" min="0" max="12" value="0" class="w-full"
                            oninput="app.updateCustom('hours', this.value, 500, 'extra hours')">
                        <p class="text-sm text-gray-600 mt-2">₱500 per extra hour</p>
                    </div>

                    <div>
                        <div class="flex justify-between mb-4">
                            <label class="font-bold text-gray-900">Additional Shooters</label>
                            <span id="display-photographers" class="font-bold text-[#dc143c]">Standard Crew</span>
                        </div>
                        <input type="range" id="input-photographers" min="0" max="4" value="0" class="w-full"
                            oninput="app.updateCustom('photographers', this.value, 1500, 'shooters')">
                        <p class="text-sm text-gray-600 mt-2">₱1,500 per additional person</p>
                    </div>

                    <div>
                        <div class="flex justify-between mb-4">
                            <label class="font-bold text-gray-900">Extra Edited Photos</label>
                            <span id="display-photos" class="font-bold text-[#dc143c]">Standard Amount</span>
                        </div>
                        <input type="range" id="input-photos" min="0" max="200" step="10" value="0" class="w-full"
                            oninput="app.updateCustom('photos', this.value, 20, 'photos')">
                        <p class="text-sm text-gray-600 mt-2">₱20 per extra photo</p>
                    </div>
                </div>
            </div>

            <!-- STEP 4: FEATURES -->
            <div id="step-4" class="step-content">
                <h2 class="text-3xl font-bold text-gray-900 mb-2">Additional Features</h2>
                <p class="text-gray-600 mb-8">Enhance your experience.</p>

                <div id="features" class="space-y-4">





                </div>
            </div>

            <!-- STEP 5: DETAILS -->
            <div id="step-5" class="step-content">
                <h2 class="text-3xl font-bold text-gray-900 mb-2">Event Details</h2>
                <p class="text-gray-600 mb-8">Tell us about your special day.</p>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div class="col-span-1 md:col-span-2 border-t pt-4">
                        <h3 class="font-bold text-gray-900 mb-2">Logistics</h3>
                    </div>
                    <div>
                        <label class="block text-sm font-bold text-gray-700 mb-1">Event Type *</label>
                        <select id="inp-type" class="w-full p-3 bg-gray-50 border border-gray-300 rounded-lg focus:border-[#dc143c] outline-none">
                            <option value="">Select type</option>
                            
                        </select>
                    </div>
                    <div>
                        <label class="block text-sm font-bold text-gray-700 mb-1">Venue *</label>
                        <input type="text" id="inp-location" class="w-full p-3 bg-gray-50 border border-gray-300 rounded-lg focus:border-[#dc143c] outline-none" required>
                    </div>
                    <div>
                        <label class="block text-sm font-bold text-gray-700 mb-1">Date *</label>
                        <input type="date" id="inp-date" class="w-full p-3 bg-gray-50 border border-gray-300 rounded-lg focus:border-[#dc143c] outline-none">
                    </div>
                    <div>
                        <label class="block text-sm font-bold text-gray-700 mb-1">Time *</label>
                        <input type="time" id="inp-time" class="w-full p-3 bg-gray-50 border border-gray-300 rounded-lg focus:border-[#dc143c] outline-none">
                    </div>
                </div>
            </div>

            <!-- STEP 6: REVIEW -->
            <div id="step-6" class="step-content">
                <h2 class="text-3xl font-bold text-gray-900 mb-2">Review Booking</h2>
                <div class="bg-white border-2 border-[#dc143c] rounded-2xl overflow-hidden shadow-lg mt-6">
                    <div class="bg-[#dc143c] text-white p-6 font-bold text-xl">Booking Summary</div>
                    <div class="p-6 space-y-4">
                        <!-- Filled by JS -->
                        <div class="flex items-center gap-4 pb-4 border-b">
                            <div class="w-16 h-16 bg-gray-200 rounded-full overflow-hidden">
                                <img id="review-img" src="" class="w-full h-full object-cover">
                            </div>
                            <div>
                                <div class="text-xs uppercase font-bold text-gray-500">Photographer</div>
                                <div id="review-photographer" class="font-bold text-lg">Not Selected</div>
                            </div>
                        </div>

                        <div class="grid grid-cols-2 gap-4 pb-4 border-b text-sm">
                            <div><span class="block text-gray-500 font-bold text-xs uppercase">Event</span> <span id="review-type" class="font-bold"></span></div>
                            <div><span class="block text-gray-500 font-bold text-xs uppercase">Date</span> <span id="review-date" class="font-bold"></span></div>
                            <div class="col-span-2"><span class="block text-gray-500 font-bold text-xs uppercase">Location</span> <span id="review-location" class="font-bold"></span></div>
                        </div>

                        <div id="review-items" class="space-y-2 text-sm"></div>

                        <div class="border-t pt-4 flex justify-between items-center">
                            <span class="font-bold text-xl">Total Investment</span>
                            <span id="review-total" class="font-bold text-3xl text-[#dc143c]">₱0</span>
                        </div>
                    </div>
                </div>
            </div>

            <!-- SUCCESS STATE -->
            <div id="step-success" class="hidden text-center py-10">
                <div class="w-24 h-24 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6">
                    <svg class="w-12 h-12 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                    </svg>
                </div>
                <h2 class="text-3xl font-bold mb-2">Booking Confirmed!</h2>
                <p class="text-gray-600 mb-8">Ref: <span id="booking-ref" class="font-mono font-bold text-[#dc143c]"></span></p>
                <button onclick="location.reload()" class="px-8 py-3 bg-[#dc143c] text-white rounded-full font-bold">Book Another</button>
            </div>

            <!-- Navigation Buttons -->
            <div id="nav-container" class="mt-auto pt-8 flex gap-4">
                <button id="btn-next" onclick="app.nextStep()" class="flex-1 py-4 bg-[#dc143c] text-white rounded-xl font-bold shadow-lg hover:bg-[#b01030] disabled:opacity-50 disabled:cursor-not-allowed transition-all">Next Step</button>
            </div>

        </div>
    </div>

    <!-- Floating Price -->
    <div id="floating-price" class="fixed bottom-6 right-6 bg-[#dc143c] text-white py-4 px-6 rounded-2xl shadow-xl z-50">
        <div class="text-xs uppercase font-bold opacity-90">Total Estimate</div>
        <div class="text-2xl font-bold">₱<span id="float-total">0</span></div>
    </div>

    <?= import_packages("datatable", "tyrax", "loading", "ctr", "path", "twal") ?>





    <script>
        addEventListener("DOMContentLoaded", () => {

        })
    </script>








    <script>
        addEventListener("DOMContentLoaded", function() {
            tyrax.get({
                url: "customizationpack/get",
                request: {
                    user: localStorage.getItem("id")
                },
                response: (send) => {
                    let data = send.data;
                    if (data.length == 0) {
                        return;
                    }
                    //document.getElementById('request_container').innerHTML = '<div class="no-order">No request orders yet</div>';
                    data.forEach(column => {
                        let container = "#";
                        let category = column.category;

                        if (category == "cov") {
                            container = '#coveragestep';
                        }

                        if (category == "pre") {
                            container = '#preevent';
                        }

                        if (category == "equip") {
                            container = '#equipment';
                        }

                        if (category == "feat") {
                            container = '#features';
                        }

                        document.querySelector(container).innerHTML = ""
                        CTR.add_html(container, `
                            <div  class="service-card flex items-center p-5 rounded-xl border-2 border-gray-200 hover:bg-gray-50 cursor-pointer transition-all"
                            onclick="app.toggleSelection(this, 'service')" data-id="${column.id}" data-price="${column.price}" data-name="${column.name}">
                        <div class="w-6 h-6 rounded border-2 border-gray-300 mr-4 flex-shrink-0 flex items-center justify-center checkbox-ui"></div>
                            <div class="flex-1">
                                <h4 class="font-bold text-lg">${column.name}</h4>
                                <p class="text-sm text-gray-600">${column.description} (${column.id})</p>
                            </div>
                            <div class="text-[#dc143c] font-bold text-lg ml-4">₱${column.price}</div>
                            </div>
                        
                        `)
                    });
                },
            })
        })
    </script>






    <script>
        let basket = [];

        function displayAllphotographers(searchTerm = '') {
            tyrax.get({
                url: "admin/get",
                response: (send) => {
                    let data = send.data;
                    data.forEach(column => {
                        const imageSrc = column.img || "<?= assets('img/placeholder.png') ?>";
                        const name = column.name;
                        const lname = column.lname;
                        const skill = column.skill;
                        const status = column.status;
                        const user_id = column.user_id;

                        basket[user_id] = {
                            name: name,
                            lname: lname,
                            status: status,
                            skill: skill,
                            user_id: user_id

                        }
                        DOM.add_html("#profilephotgrapher", `
                        <div class="photographer-card relative group cursor-pointer rounded-xl border-2 border-gray-200 bg-white hover:border-red-300 hover:shadow-lg transition-all h-full flex flex-col overflow-hidden"
                        onclick="app.selectPhotographer('p1', this)" data-name="${name} ${lname}" data-id="${user_id}">
                        <div class="relative h-64">
                            <img src="${imageSrc}" class="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110">
                            <div class="absolute top-3 right-3 bg-white/90 px-2 py-1 rounded-lg text-sm font-bold flex items-center gap-1">★ 4.9</div>
                        </div>
                        <div class="p-5 flex-1 flex flex-col">
                            <h3 class="text-xl font-bold mb-1">${name} ${lname} (${user_id})</h3>
                            
                            <p class="text-sm text-gray-600 mb-4 flex-1">${column.description}</p>
                            <div class="flex flex-wrap gap-1">
                                <span class="text-xs bg-gray-100 px-2 py-1 rounded">${skill}</span>
                            </div>
                        </div>
                        <!-- Hidden Check Icon -->
                        <div class="check-icon hidden absolute top-3 left-3 bg-[#dc143c] text-white p-1 rounded-full shadow-lg">
                            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3">
                                <polyline points="20 6 9 17 4 12" />
                            </svg>
                        </div>
                    </div>`)
                    });
                },
            })
        }


        window.addEventListener("DOMContentLoaded", function() {
            displayAllphotographers();
        });
    </script>


<script>
    addEventListener("DOMContentLoaded",function(){
        tyrax.get({
            url:"services/get",
            //inspect:true,
            response:(send)=>{
                let data = send.data;
                
                data.forEach(column => {
                    DOM.add_html("#inp-type",`
                    <option value="${column.servicesID}">${column.services_name}</option>
                    `)
                });
            },

        })
    })
</script>




    <script>
        class App {
            constructor() {
                this.selected ={};
                this.step = 1;
                this.totalSteps = 6;
                this.state = {
                    photographer: null, // DOM element
                    photo_id: null,
                    services: new Set(), // Set of DOM elements
                    features: new Set(), // Set of DOM elements
                    custom: {
                        hours: {
                            val: 0,
                            price: 0
                        },
                        photographers: {
                            val: 0,
                            price: 0
                        },
                        photos: {
                            val: 0,
                            price: 0
                        }
                    }
                };
                this.updateUI();
            }

            // --- Navigation ---
            nextStep() {
                if (this.step === 5 && !this.validateDetails()) return;

                if (this.step < this.totalSteps) {
                    this.step++;
                    this.updateUI();
                    window.scrollTo({
                        top: 0,
                        behavior: 'smooth'
                    });
                } else {
                    this.submit();
                }
            }

            prevStep() {
                if (this.step > 1) {
                    this.step--;
                    this.updateUI();
                    window.scrollTo({
                        top: 0,
                        behavior: 'smooth'
                    });
                }
            }

            updateUI() {
                // Steps Visibility
                document.querySelectorAll('.step-content').forEach((el, idx) => {
                    const stepNum = idx + 1;
                    if (stepNum === this.step) el.classList.add('active');
                    else el.classList.remove('active');
                });

                // Progress Bara
                const pct = ((this.step - 1) / (this.totalSteps - 1)) * 100;
                document.getElementById('progress-bar').style.width = pct + '%';

                document.querySelectorAll('.step-indicator').forEach(el => {
                    const s = parseInt(el.dataset.step);
                    const circle = el.querySelector('div');
                    const label = el.querySelector('span');

                    if (s === this.step) {
                        circle.className = "w-10 h-10 rounded-full flex items-center justify-center font-bold text-sm border-2 bg-[#dc143c] border-[#dc143c] text-white transition-all scale-110 shadow-lg";
                        label.className = "mt-2 text-xs font-bold text-[#dc143c]";
                    } else if (s < this.step) {
                        circle.className = "w-10 h-10 rounded-full flex items-center justify-center font-bold text-sm border-2 bg-[#1a1a1a] border-[#1a1a1a] text-white transition-all";
                        label.className = "mt-2 text-xs font-medium text-[#1a1a1a]";
                    } else {
                        circle.className = "w-10 h-10 rounded-full flex items-center justify-center font-bold text-sm border-2 bg-white border-gray-300 text-gray-400 transition-all";
                        label.className = "mt-2 text-xs font-medium text-gray-400";
                    }
                });

                // Button State
                const btnNext = document.getElementById('btn-next');
                const btnBack = document.getElementById('global-back');

                btnBack.classList.toggle('hidden', this.step === 1);

                if (this.step === 1 && !this.state.photographer) btnNext.disabled = true;
                else if (this.step === 2 && this.state.services.size === 0) btnNext.disabled = true;
                else btnNext.disabled = false;

                btnNext.innerText = this.step === 6 ? 'Confirm Booking' : 'Next Step';

                if (this.step === 6) this.renderReview();

                // Hide floating price on review
                document.getElementById('floating-price').classList.toggle('hidden', this.step === 6);
            }


            // --- Logic ---
            selectPhotographer(id, el) {
                // Deselect others
                document.querySelectorAll('.photographer-card').forEach(c => {
                    c.classList.remove('selected-card', 'ring-2', 'ring-[#dc143c]');
                    c.querySelector('.check-icon').classList.add('hidden');
                });
                // Select clicked
                el.classList.add('selected-card', 'ring-2', 'ring-[#dc143c]');
                el.querySelector('.check-icon').classList.remove('hidden');

                this.state.photographer = el;
                this.updateUI();
            }

            toggleSelection(el, type) {
                const set = type === 'service' ? this.state.services : this.state.features;

                if (set.has(el)) {
                    set.delete(el);
                    el.classList.remove('selected-card');
                    el.querySelector('.checkbox-ui').innerHTML = '';
                    el.querySelector('.checkbox-ui').classList.remove('bg-[#dc143c]', 'border-[#dc143c]');
                    el.querySelector('.checkbox-ui').classList.add('border-gray-300');
                } else {
                    set.add(el);
                    el.classList.add('selected-card');
                    el.querySelector('.checkbox-ui').innerHTML = '<svg class="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M5 13l4 4L19 7"/></svg>';
                    el.querySelector('.checkbox-ui').classList.remove('border-gray-300');
                    el.querySelector('.checkbox-ui').classList.add('bg-[#dc143c]', 'border-[#dc143c]');
                }

                this.calculateTotal();
                if (type === 'service') this.updateUI(); // Check validation
            }

            updateCustom(key, val, pricePerUnit, labelSuffix) {
                const num = parseInt(val);
                this.state.custom[key] = {
                    val: num,
                    price: num * pricePerUnit
                };

                // Update Label Text directly
                const label = document.getElementById(`display-${key}`);
                if (num === 0) label.innerText = key === 'hours' ? 'No extra hours' : (key === 'photographers' ? 'Standard Crew' : 'Standard Amount');
                else label.innerText = `+ ${num} ${labelSuffix}`;

                this.calculateTotal();
            }

            calculateTotal() {
                let total = 0;
                this.state.services.forEach(el => total += parseInt(el.dataset.price));
                this.state.features.forEach(el => total += parseInt(el.dataset.price));
                Object.values(this.state.custom).forEach(o => total += o.price);

                document.getElementById('float-total').innerText = total.toLocaleString();
                return total;
            }

            validateDetails() {
                const req = ['inp-type', 'inp-location', 'inp-date', 'inp-time'];
                let valid = true;
                req.forEach(id => {
                    const el = document.getElementById(id);
                    if (!el.value) {
                        el.classList.add('border-red-500');
                        valid = false;
                    } else {
                        el.classList.remove('border-red-500');
                    }
                });
                if (!valid) alert('Please fill in all required fields');
                return valid;
            }

            renderReview() {
                //console.log(p.dataset.name);
                const p = this.state.photographer;
                document.getElementById('review-photographer').innerText = p.dataset.name;
                let pid = p.dataset.id;
                document.getElementById('review-img').src = p.querySelector('img').src;

                document.getElementById('review-type').innerText = document.getElementById('inp-type').selectedOptions[0].text;
                document.getElementById('review-location').innerText = document.getElementById('inp-location').value;
                document.getElementById('review-date').innerText = document.getElementById('inp-date').value + ' @ ' + document.getElementById('inp-time').value;

                let html = '';
                // Services
                let mga_napili_s = [];
                this.state.services.forEach(el => {
                    html += `<div class="flex justify-between"><span class="text-gray-800">${el.dataset.name}</span><span class="font-bold">₱${parseInt(el.dataset.price).toLocaleString()}</span></div>`;
                    mga_napili_s[el.dataset.id] = el.dataset.name;
                    console.log(mga_napili_s);
                });
                // Custom
                if (this.state.custom.hours.val > 0) html += `<div class="flex justify-between"><span class="text-gray-800">Extra Hours (${this.state.custom.hours.val})</span><span class="font-bold">₱${this.state.custom.hours.price.toLocaleString()}</span></div>`;
                if (this.state.custom.photographers.val > 0) html += `<div class="flex justify-between"><span class="text-gray-800">Extra Shooters (${this.state.custom.photographers.val})</span><span class="font-bold">₱${this.state.custom.photographers.price.toLocaleString()}</span></div>`;
                if (this.state.custom.photos.val > 0) html += `<div class="flex justify-between"><span class="text-gray-800">Extra Photos (${this.state.custom.photos.val})</span><span class="font-bold">₱${this.state.custom.photos.price.toLocaleString()}</span></div>`;
                
                
                // Features
                let mga_napili_f = [];
                this.state.features.forEach(el => {
                    html += `<div class="flex justify-between"><span class="text-gray-800">+ ${el.dataset.name}</span><span class="font-bold">₱${parseInt(el.dataset.price).toLocaleString()}</span></div>`;
                    mga_napili_f[el.dataset.id] = el.dataset.name;
                    console.log(mga_napili_f);
                });


                document.getElementById('review-items').innerHTML = html;
                document.getElementById('review-total').innerText = '₱' + this.calculateTotal().toLocaleString();



             this.selected = {
                    photgrapher: pid,
                    photoname: p.dataset.name,
                    packages: mga_napili_s,
                    location: document.getElementById('inp-location').value,
                    services: document.getElementById('inp-type').value,
                    date_time: document.getElementById('inp-date').value + ' @ ' + document.getElementById('inp-time').value,
                    addhrs: this.state.custom.hours.val,
                    addshooter: this.state.custom.photographers.val,
                    extraphot: this.state.custom.photos.val,
                    customer: localStorage.getItem("id"),
                    total: this.calculateTotal(),
                    

                    

                };
                console.log(this.selected);
                
            }

            submit() {

                submitOrder(this.selected);
                const ref = Math.floor(Math.random() * 10000).toString().padStart(4, '0');
                document.getElementById('booking-ref').innerText = '#PH-2025-' + ref;
                // Hide main steps, show success
                document.querySelectorAll('.step-content').forEach(el => el.style.display = 'none');
                document.getElementById('nav-container').style.display = 'none';
                document.getElementById('step-indicators').parentElement.style.display = 'none';
                document.getElementById('global-back').style.display = 'none';

                document.getElementById('step-success').classList.remove('hidden');
                document.getElementById('step-success').classList.add('active');
            }
        }

        function submitOrder(selected) {
                    tyrax.post({
                        url: "bookpack/add",
                        data: selected,
                        //test:true,
                        response: (send) => {
                            if (send.code == 200) {
                                twal.ok("Booking submitted successfully").then(() => location.href = "?page=users/home")
                            } else {
                                twal.err(send.message);
                            }
                        }
                    })
                }
        // Initialize Input Date Min
        document.getElementById('inp-date').min = new Date().toISOString().split('T')[0];

        const app = new App();
    </script>
</body>

</html>